config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users
  #root to: "index#home"
  
  # scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

  root to: "index#startpage"
  get '/home', to: 'index#home', as: :home
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    post '/users/sign_out', to: 'users/sessions#destroy' 
  end

  # resources :films do
  #   resources :ratings, only: [:create]
  # end

  post '/ratings/new', to: 'ratings#create' 
  get '/like', to: 'user_likes#create', as: :like
  get '/unlike', to: 'user_likes#destroy', as: :unlike
  get '/later', to: 'user_watch_laters#create', as: :later
  get '/not_later', to: 'user_watch_laters#destroy', as: :not_later

  resources :ratings
  resources :comments
  resources :user_likes
  resources :user_watch_laters
  resources :user_histories
  resources :user_profiles
  resources :users
  resources :genre_films
  resources :country_films
  resources :cast_films
  resources :films
  resources :maturity_ratings
  resources :genres
  resources :countries
  resources :casts
  resources :roles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # end
end

app/models/country_film.rb
# frozen_string_literal: true

class CountryFilm < ApplicationRecord
  belongs_to :country
  belongs_to :film
end

app/controllers/country_films_controller.rb
# frozen_string_literal: true

class CountryFilmsController < ApplicationController
  before_action :set_country_film, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /country_films or /country_films.json
  def index
    @country_films = CountryFilm.all
  end

  # GET /country_films/1 or /country_films/1.json
  def show; end

  # GET /country_films/new
  def new
    @country_film = CountryFilm.new
  end

  # GET /country_films/1/edit
  def edit; end

  # POST /country_films or /country_films.json
  def create
    @country_film = CountryFilm.new(country_film_params)

    respond_to do |format|
      if @country_film.save
        format.html { redirect_to country_film_url(@country_film), notice: "Country film was successfully created." }
        format.json { render :show, status: :created, location: @country_film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country_film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /country_films/1 or /country_films/1.json
  def update
    respond_to do |format|
      if @country_film.update(country_film_params)
        format.html { redirect_to country_film_url(@country_film), notice: "Country film was successfully updated." }
        format.json { render :show, status: :ok, location: @country_film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country_film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /country_films/1 or /country_films/1.json
  def destroy
    @country_film.destroy!

    respond_to do |format|
      format.html { redirect_to country_films_url, notice: "Country film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_country_film
    @country_film = CountryFilm.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def country_film_params
    params.require(:country_film).permit(:country_id, :film_id)
  end
end

app/helpers/country_films_helper.rb
# frozen_string_literal: true

module CountryFilmsHelper
end

app/views/country_films/_country_film.html.erb
<div id="<%= dom_id country_film %>">
  <p>
    <strong>Country:</strong>
    <%= country_film.country_id %>
  </p>

  <p>
    <strong>Film:</strong>
    <%= country_film.film_id %>
  </p>

</div>

app/views/country_films/_form.html.erb
<%= form_with(model: country_film) do |form| %>
  <% if country_film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(country_film.errors.count, "error") %> prohibited this country_film from being saved:</h2>

      <ul>
        <% country_film.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :country_id, style: "display: block" %>
    <%= form.text_field :country_id %>
  </div>

  <div>
    <%= form.label :film_id, style: "display: block" %>
    <%= form.text_field :film_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/country_films/edit.html.erb
<h1>Editing country film</h1>

<%= render "form", country_film: @country_film %>

<br>

<div>
  <%= link_to "Show this country film", @country_film %> |
  <%= link_to "Back to country films", country_films_path %>
</div>

app/views/country_films/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Country films</h1>

<div id="country_films">
  <% @country_films.each do |country_film| %>
    <%= render country_film %>
    <p>
      <%= link_to "Show this country film", country_film %>
    </p>
  <% end %>
</div>

<%= link_to "New country film", new_country_film_path %>

app/views/country_films/new.html.erb
<h1>New country film</h1>

<%= render "form", country_film: @country_film %>

<br>

<div>
  <%= link_to "Back to country films", country_films_path %>
</div>

app/views/country_films/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @country_film %>

<div>
  <%= link_to "Edit this country film", edit_country_film_path(@country_film) %> |
  <%= link_to "Back to country films", country_films_path %>

  <%= button_to "Destroy this country film", @country_film, method: :delete %>
</div>