config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users
  #root to: "index#home"
  
  # scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

  root to: "index#startpage"
  get '/home', to: 'index#home', as: :home
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    post '/users/sign_out', to: 'users/sessions#destroy' 
  end

  # resources :films do
  #   resources :ratings, only: [:create]
  # end

  post '/ratings/new', to: 'ratings#create' 
  get '/like', to: 'user_likes#create', as: :like
  get '/unlike', to: 'user_likes#destroy', as: :unlike
  get '/later', to: 'user_watch_laters#create', as: :later
  get '/not_later', to: 'user_watch_laters#destroy', as: :not_later

  resources :ratings
  resources :comments
  resources :user_likes
  resources :user_watch_laters
  resources :user_histories
  resources :user_profiles
  resources :users
  resources :genre_films
  resources :country_films
  resources :cast_films
  resources :films
  resources :maturity_ratings
  resources :genres
  resources :countries
  resources :casts
  resources :roles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # end
end

app/models/genre_film.rb
# frozen_string_literal: true

class GenreFilm < ApplicationRecord
  belongs_to :genre
  belongs_to :film
end

app/controllers/genre_films_controller.rb
# frozen_string_literal: true

class GenreFilmsController < ApplicationController
  before_action :set_genre_film, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /genre_films or /genre_films.json
  def index
    @genre_films = GenreFilm.all
  end

  # GET /genre_films/1 or /genre_films/1.json
  def show; end

  # GET /genre_films/new
  def new
    @genre_film = GenreFilm.new
  end

  # GET /genre_films/1/edit
  def edit; end

  # POST /genre_films or /genre_films.json
  def create
    @genre_film = GenreFilm.new(genre_film_params)

    respond_to do |format|
      if @genre_film.save
        format.html { redirect_to genre_film_url(@genre_film), notice: "Genre film was successfully created." }
        format.json { render :show, status: :created, location: @genre_film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre_film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genre_films/1 or /genre_films/1.json
  def update
    respond_to do |format|
      if @genre_film.update(genre_film_params)
        format.html { redirect_to genre_film_url(@genre_film), notice: "Genre film was successfully updated." }
        format.json { render :show, status: :ok, location: @genre_film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre_film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genre_films/1 or /genre_films/1.json
  def destroy
    @genre_film.destroy!

    respond_to do |format|
      format.html { redirect_to genre_films_url, notice: "Genre film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_genre_film
    @genre_film = GenreFilm.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def genre_film_params
    params.require(:genre_film).permit(:genre_id, :film_id)
  end
end

app/helpers/genre_films_helper.rb
# frozen_string_literal: true

module GenreFilmsHelper
end

app/views/genre_films/_form.html.erb
<%= form_with(model: genre_film) do |form| %>
  <% if genre_film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(genre_film.errors.count, "error") %> prohibited this genre_film from being saved:</h2>

      <ul>
        <% genre_film.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :genre_id, style: "display: block" %>
    <%= form.text_field :genre_id %>
  </div>

  <div>
    <%= form.label :film_id, style: "display: block" %>
    <%= form.text_field :film_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/genre_films/_genre_film.html.erb
<div id="<%= dom_id genre_film %>">
  <p>
    <strong>Genre:</strong>
    <%= genre_film.genre_id %>
  </p>

  <p>
    <strong>Film:</strong>
    <%= genre_film.film_id %>
  </p>

</div>

app/views/genre_films/edit.html.erb
<h1>Editing genre film</h1>

<%= render "form", genre_film: @genre_film %>

<br>

<div>
  <%= link_to "Show this genre film", @genre_film %> |
  <%= link_to "Back to genre films", genre_films_path %>
</div>

app/views/genre_films/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Genre films</h1>

<div id="genre_films">
  <% @genre_films.each do |genre_film| %>
    <%= render genre_film %>
    <p>
      <%= link_to "Show this genre film", genre_film %>
    </p>
  <% end %>
</div>

<%= link_to "New genre film", new_genre_film_path %>

app/views/genre_films/new.html.erb
<h1>New genre film</h1>

<%= render "form", genre_film: @genre_film %>

<br>

<div>
  <%= link_to "Back to genre films", genre_films_path %>
</div>

app/views/genre_films/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @genre_film %>

<div>
  <%= link_to "Edit this genre film", edit_genre_film_path(@genre_film) %> |
  <%= link_to "Back to genre films", genre_films_path %>

  <%= button_to "Destroy this genre film", @genre_film, method: :delete %>
</div>