config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users
  #root to: "index#home"
  
  # scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

  root to: "index#startpage"
  get '/home', to: 'index#home', as: :home
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    post '/users/sign_out', to: 'users/sessions#destroy' 
  end

  # resources :films do
  #   resources :ratings, only: [:create]
  # end

  post '/ratings/new', to: 'ratings#create' 
  get '/like', to: 'user_likes#create', as: :like
  get '/unlike', to: 'user_likes#destroy', as: :unlike
  get '/later', to: 'user_watch_laters#create', as: :later
  get '/not_later', to: 'user_watch_laters#destroy', as: :not_later

  resources :ratings
  resources :comments
  resources :user_likes
  resources :user_watch_laters
  resources :user_histories
  resources :user_profiles
  resources :users
  resources :genre_films
  resources :country_films
  resources :cast_films
  resources :films
  resources :maturity_ratings
  resources :genres
  resources :countries
  resources :casts
  resources :roles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # end
end

app/models/rating.rb
# frozen_string_literal: true

class Rating < ApplicationRecord
  belongs_to :user_profile
  belongs_to :film

  MAX_RATING = 5
  validates :score, numericality: { in: 0..MAX_RATING }
  
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "film_id", "id", "id_value", "score", "updated_at", "user_profile_id"]
  end
end

app/controllers/ratings_controller.rb
# frozen_string_literal: true
class RatingsController < ApplicationController
  before_action :set_rating, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /ratings or /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1 or /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings or /ratings.json
  # def create
  #   @rating = Rating.new(rating_params)

  #   respond_to do |format|
  #     if @rating.save
  #       format.html { redirect_to rating_url(@rating), notice: "Rating was successfully created." }
  #       format.json { render :show, status: :created, location: @rating }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @rating.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def create
    @film = Film.find(params[:film_id])
    @rating = Rating.find_or_create_by(film_id: @film.id, user_profile_id: session[:user_id])
    @rating.update(score: params[:score].to_i)
    redirect_to @film
  end

  # def create
  #   @film = Film.find(params[:film_id])
  #   @rating = Rating.find_or_create_by(film_id: @film.id, user_profile_id: session[:user_id].id)
  #   if @rating.update(score: params[:rating][:score])
  #     redirect_to @film, notice: 'Rating was successfully updated.'
  #   else
  #     redirect_to @film, alert: 'Rating could not be updated.'
  #   end
  # end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to rating_url(@rating), notice: "Rating was successfully updated." }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1 or /ratings/1.json
  def destroy
    @rating.destroy!

    respond_to do |format|
      format.html { redirect_to ratings_url, notice: "Rating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rating_params
      params.require(:rating).permit(:user_profile_id, :film_id, :score)
    end
end

app/helpers/ratings_helper.rb
# frozen_string_literal: true

module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_with(model: rating) do |form| %>
  <% if rating.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
        <% rating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_profile_id, style: "display: block" %>
    <%= form.text_field :user_profile_id %>
  </div>

  <div>
    <%= form.label :film_id, style: "display: block" %>
    <%= form.text_field :film_id %>
  </div>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.number_field :score %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ratings/_rating.html.erb
<div id="<%= dom_id rating %>">
  <p>
    <strong>User profile:</strong>
    <%= rating.user_profile_id %>
  </p>

  <p>
    <strong>Film:</strong>
    <%= rating.film_id %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= rating.score %>
  </p>

</div>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Show this rating", @rating %> |
  <%= link_to "Back to ratings", ratings_path %>
</div>

app/views/ratings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ratings</h1>

<div id="ratings">
  <% @ratings.each do |rating| %>
    <%= render rating %>
    <p>
      <%= link_to "Show this rating", rating %>
    </p>
  <% end %>
</div>

<%= link_to "New rating", new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Back to ratings", ratings_path %>
</div>

app/views/ratings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rating %>

<div>
  <%= link_to "Edit this rating", edit_rating_path(@rating) %> |
  <%= link_to "Back to ratings", ratings_path %>

  <%= button_to "Destroy this rating", @rating, method: :delete %>
</div>