config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users
  #root to: "index#home"
  
  # scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

  root to: "index#startpage"
  get '/home', to: 'index#home', as: :home
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    post '/users/sign_out', to: 'users/sessions#destroy' 
  end

  # resources :films do
  #   resources :ratings, only: [:create]
  # end

  post '/ratings/new', to: 'ratings#create' 
  get '/like', to: 'user_likes#create', as: :like
  get '/unlike', to: 'user_likes#destroy', as: :unlike
  get '/later', to: 'user_watch_laters#create', as: :later
  get '/not_later', to: 'user_watch_laters#destroy', as: :not_later

  resources :ratings
  resources :comments
  resources :user_likes
  resources :user_watch_laters
  resources :user_histories
  resources :user_profiles
  resources :users
  resources :genre_films
  resources :country_films
  resources :cast_films
  resources :films
  resources :maturity_ratings
  resources :genres
  resources :countries
  resources :casts
  resources :roles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # end
end

app/models/cast_film.rb
# frozen_string_literal: true

class CastFilm < ApplicationRecord
  belongs_to :cast
  belongs_to :film
end

app/controllers/cast_films_controller.rb
# frozen_string_literal: true

class CastFilmsController < ApplicationController
  before_action :set_cast_film, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /cast_films or /cast_films.json
  def index
    @cast_films = CastFilm.all
  end

  # GET /cast_films/1 or /cast_films/1.json
  def show; end

  # GET /cast_films/new
  def new
    @cast_film = CastFilm.new
  end

  # GET /cast_films/1/edit
  def edit; end

  # POST /cast_films or /cast_films.json
  def create
    @cast_film = CastFilm.new(cast_film_params)

    respond_to do |format|
      if @cast_film.save
        format.html { redirect_to cast_film_url(@cast_film), notice: "Cast film was successfully created." }
        format.json { render :show, status: :created, location: @cast_film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cast_film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cast_films/1 or /cast_films/1.json
  def update
    respond_to do |format|
      if @cast_film.update(cast_film_params)
        format.html { redirect_to cast_film_url(@cast_film), notice: "Cast film was successfully updated." }
        format.json { render :show, status: :ok, location: @cast_film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cast_film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cast_films/1 or /cast_films/1.json
  def destroy
    @cast_film.destroy!

    respond_to do |format|
      format.html { redirect_to cast_films_url, notice: "Cast film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cast_film
    @cast_film = CastFilm.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cast_film_params
    params.require(:cast_film).permit(:cast_id, :film_id)
  end
end

app/helpers/cast_films_helper.rb
# frozen_string_literal: true

module CastFilmsHelper
end

app/views/cast_films/_cast_film.html.erb
<div id="<%= dom_id cast_film %>">
  <p>
    <strong>Cast:</strong>
    <%= cast_film.cast_id %>
  </p>

  <p>
    <strong>Film:</strong>
    <%= cast_film.film_id %>
  </p>

</div>

app/views/cast_films/_form.html.erb
<%= form_with(model: cast_film) do |form| %>
  <% if cast_film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cast_film.errors.count, "error") %> prohibited this cast_film from being saved:</h2>

      <ul>
        <% cast_film.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cast_id, style: "display: block" %>
    <%= form.text_field :cast_id %>
  </div>

  <div>
    <%= form.label :film_id, style: "display: block" %>
    <%= form.text_field :film_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cast_films/edit.html.erb
<h1>Editing cast film</h1>

<%= render "form", cast_film: @cast_film %>

<br>

<div>
  <%= link_to "Show this cast film", @cast_film %> |
  <%= link_to "Back to cast films", cast_films_path %>
</div>

app/views/cast_films/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cast films</h1>

<div id="cast_films">
  <% @cast_films.each do |cast_film| %>
    <%= render cast_film %>
    <p>
      <%= link_to "Show this cast film", cast_film %>
    </p>
  <% end %>
</div>

<%= link_to "New cast film", new_cast_film_path %>

app/views/cast_films/new.html.erb
<h1>New cast film</h1>

<%= render "form", cast_film: @cast_film %>

<br>

<div>
  <%= link_to "Back to cast films", cast_films_path %>
</div>

app/views/cast_films/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cast_film %>

<div>
  <%= link_to "Edit this cast film", edit_cast_film_path(@cast_film) %> |
  <%= link_to "Back to cast films", cast_films_path %>

  <%= button_to "Destroy this cast film", @cast_film, method: :delete %>
</div>